org: buryhuang
app: tribute-api
service: tribute-api

frameworkVersion: '3'

useDotenv: true

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 60
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
